import { Service, Testimonial, Project, FAQItem } from './types';

export const BRAND_INFO = {
  name: 'Breevo Electric',
  slogan: 'Precision Engineering. Premium Service. Pure Safety.',
  tagline: 'Toronto’s Premier Electrical Specialists',
  license: 'ECRA / ESA License #7014832',
  phone: '(416) 555-0188',
  email: 'info@breevoelectric.ca',
  address: 'Engineering Headquarters',
  city: 'Toronto, Ontario, Canada',
  postalCode: '',
  mapPlaceholderUrl: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=1200',
  aboutStory: 'Founded in 2011 by Master Electrician JP Levesque, Breevo Electric was built on a simple vision: to elevate local electrical services into a high-end, seamless client experience. Combining Canadian safety standards with modern, sustainable technologies, we serve discerning homeowners, luxury custom builders, and leading commercial properties across the Greater Toronto Area (GTA). We treat your architecture with the absolute highest level of care, using premium materials, precise layouts, and surgical cleanliness.',
};

export const STATISTICS = [
  { value: '15+', label: 'Years of Excellence', suffix: '' },
  { value: '4,800', label: 'Premium Projects Completed', suffix: '+' },
  { value: '100', label: 'Safety Rating (ESA)', suffix: '%' },
  { value: '12', label: 'Certified Elite Technicians', suffix: '' },
];

export const SERVICE_CATEGORIES = [
  { id: 'all', name: 'All Services' },
  { id: 'residential', name: 'Residential' },
  { id: 'commercial', name: 'Commercial' },
  { id: 'specialty', name: 'Specialty & EV' },
];

export const SERVICES: Service[] = [
  {
    id: 'panel-upgrades',
    title: 'Premium Service Panel Upgrades',
    slug: 'panel-upgrades',
    iconName: 'Cpu',
    shortDescription: 'Elevate your home’s electrical foundation from 100A to 200A or 400A with professional ESA-certified master execution.',
    longDescription: 'Modern luxury living demands seamless power. Our signature service panel upgrades replace aging or hazardous fuse boxes and 100-amp panels with industrial-grade, high-capacity electrical panels. Designed to safely support luxury appliances, hot tubs, EV chargers, and multi-zone heating, our work is meticulously structured, labeled with machine-printed precision, and completed in a single-day power shutdown window.',
    category: 'residential',
    startingPrice: '$3,800 CAD',
    features: [
      'Full 100A to 200A or 400A transitions',
      'Whole-home surge protection integration included',
      'Machine-printed, crystal-clear panel labeling',
      'Full Electrical Safety Authority (ESA) permit & inspection handling',
      'Copper-to-copper premium bonding and grounding',
    ],
    testimonial: {
      quote: 'Breevo upgraded our old Forest Hill home to 200A. The panel looks like a piece of modern art—wiring is absolutely immaculate, straight, and properly bound. Unparalleled professionalism.',
      author: 'Marcus Vance',
      location: 'Forest Hill, Toronto',
    },
  },
  {
    id: 'ev-charging',
    title: 'Elite EV Charger Stations',
    slug: 'ev-charging',
    iconName: 'Zap',
    shortDescription: 'Tesla, Porsche, and universal Level 2 smart home charger installations with custom load management.',
    longDescription: 'Charge your luxury electric vehicle at peak speeds right from your garage. We design and install dedicated Level 2 smart-charging circuits, handling complex load-management systems for homes with existing electrical constraints. Whether you drive a Tesla, Taycan, Rivian, or Audi e-tron, we provide sleek wall-mounted installations with concealed premium conduits.',
    category: 'specialty',
    startingPrice: '$1,200 CAD',
    features: [
      'Official Tesla Wall Connector certified installers',
      'Smart load management systems (DCC-9/DCC-12)',
      'Sub-panel installations for multi-vehicle charging',
      'Interior garage flush-mountings and weather-proof exterior setups',
      'Assistance with Ontario provincial green energy rebates',
    ],
    testimonial: {
      quote: 'Excellent service installing our dual Tesla Chargers. They configured a smart load-sharer so we didn’t need an immediate service upgrade. Brilliant engineering!',
      author: 'David Choy',
      location: 'Markham, ON',
    },
  },
  {
    id: 'smart-lighting',
    title: 'Architectural Lighting & Smart Controls',
    slug: 'smart-lighting',
    iconName: 'Lightbulb',
    shortDescription: 'Lutron, Control4, and architectural LED design to create stunning, ambient atmospheres throughout your estate.',
    longDescription: 'Light is the soul of architecture. We collaborate with designers and luxury homeowners to install sophisticated lighting systems. Specializing in Lutron Caséta, RA3, and Homeworks systems, we provide custom scene programming, discrete high-end designer keypads, smooth dimming curves with zero flicker, and beautiful under-cabinet, cove, and outdoor landscape lighting systems.',
    category: 'specialty',
    startingPrice: '$2,500 CAD',
    features: [
      'Lutron Certified RA3 & Homeworks system programming',
      'Architectural recess and low-profile gallery lighting',
      'Zero-flicker LED driver matching and dimming calibration',
      'Custom luxury metallic or glass keypads',
      'Landscape accent lighting and smart astronomical timers',
    ],
    testimonial: {
      quote: 'We had Lutron RA3 installed across our entire custom build. Breevo coordinated perfectly with our interior designer. The automated evening lighting scenes are breathtaking.',
      author: 'Amélie Desrosiers',
      location: 'Rosedale, Toronto',
    },
  },
  {
    id: 'commercial-fitout',
    title: 'Commercial Office & Retail Fit-outs',
    slug: 'commercial-fitout',
    iconName: 'Building2',
    shortDescription: 'High-end electrical infrastructure, dedicated server power, architectural task lighting, and retail distribution panels.',
    longDescription: 'For modern offices, boutique retail, and upscale medical clinics, we construct flawless commercial electrical backbones. From heavy-duty metal-clad conduits and distribution panels to designer commercial lighting, structured cabling, and generator backups, Breevo delivers projects on-schedule, fully compliant, and engineered for long-term operational efficiency.',
    category: 'commercial',
    startingPrice: 'By Consultation',
    features: [
      'Bespoke retail and high-end creative office power distribution',
      'Dedicated server room circuits, clean power, and UPS systems',
      'Architectural task lighting layout and energy code compliance',
      'Integrated HVAC and security control wiring',
      'Comprehensive high-voltage distribution & sub-metering',
    ],
    testimonial: {
      quote: 'We hired Breevo for our new 8,000 sq ft downtown creative agency office. From exposed cable trays to custom boardroom lighting, their workmanship is top-tier.',
      author: 'Sarah Jenkins',
      location: 'King West, Toronto',
    },
  },
  {
    id: 'aluminum-wiring',
    title: 'Aluminum Wiring Remediation',
    slug: 'aluminum-wiring',
    iconName: 'ShieldAlert',
    shortDescription: 'Safeguard your legacy home with permanent, certified AlumiConn or COPALUM crimp technologies and full safety certification.',
    longDescription: 'Many GTA homes built in the 1960s and 70s contain legacy aluminum wiring, which presents high fire risks at connection terminals. Breevo provides comprehensive aluminum remediation using approved copper-tail pig-tailing with industry-leading AlumiConn connectors. We inspect every single receptacle, switch, and junction box in your home, providing an ESA-certified safety report that satisfies Canadian insurance underwriters.',
    category: 'residential',
    startingPrice: '$3,500 CAD',
    features: [
      'Comprehensive safety inspection of all connection points',
      'Certified AlumiConn pig-tailing (approved by ESA & insurance companies)',
      'Replacement of non-co/alr rated switches and receptacles',
      'Full thermal imaging scan of high-load circuits',
      'Official ESA Certificate of Inspection for peace of mind',
    ],
    testimonial: {
      quote: 'Insurance company threatened to cancel our policy due to aluminum wiring. Breevo remidatied the entire house in 3 days, clean and quiet. Got our ESA cert and saved our policy!',
      author: 'Robert Higgins',
      location: 'Oakville, ON',
    },
  },
  {
    id: 'emergency-repairs',
    title: 'Urgent Troubleshooting & Repair',
    slug: 'emergency-repairs',
    iconName: 'Activity',
    shortDescription: 'Prompt diagnostic response for circuit failures, power outages, and electrical hazards by master technicians.',
    longDescription: 'When power failure strikes or hazardous sparks occur, you need immediate elite expertise. Our master technicians carry advanced thermal imaging cameras and specialized diagnostic tools to trace faults in minutes. We isolate, repair, and certify the fix immediately, ensuring the safety of your family or business premises.',
    category: 'residential',
    startingPrice: '$180/hr CAD',
    features: [
      'Advanced thermal imaging diagnostic cameras',
      'Rapid fault detection and circuit isolation',
      'On-the-spot code violation remediation',
      'Complete emergency generator hookups and transfer switches',
      'Transparent diagnostic summaries and safe solutions',
    ],
    testimonial: {
      quote: 'A hidden short circuit took out power to half our first floor. Breevo arrived within two hours, located the faulty wire behind a kitchen wall with an infrared scanner, and fixed it instantly.',
      author: 'Elena Petrova',
      location: 'The Kingsway, Toronto',
    },
  },
  {
    id: 'pool-hot-tub',
    title: 'Luxury Pool & Hot Tub Wiring',
    slug: 'pool-hot-tub',
    iconName: 'Waves',
    shortDescription: 'Waterfront-grade sub-panels, pool automation integration, and strict safety GFCI grounding systems.',
    longDescription: 'Water and electricity demand zero margin of error. We specialize in code-compliant premium wiring for pools, swim spas, hot tubs, and cabanas. We install outdoor weather-proof sub-panels, configure automated smart pool-heater integrations, lay buried heavy-gauge feeder cables, and carry out extensive equipotential bonding to guarantee the absolute safety of your swimming areas.',
    category: 'specialty',
    startingPrice: '$1,900 CAD',
    features: [
      'Equipotential bonding grids for absolute water safety',
      'Certified GFCI breaker safety systems',
      'Buried conduit trenching with high-durability UF feeders',
      'Outdoor cabana and automated ambient lighting integration',
      'Pool heater, heat pump, and salt-chlorinator dedicated connections',
    ],
    testimonial: {
      quote: 'Breevo wired our luxury fiberglass pool and cabana in Mississauga. Flawless execution. They handled the city permits, buried the lines perfectly, and set up our automated light shows.',
      author: 'Gurpreet Singh',
      location: 'Mississauga, ON',
    },
  },
  {
    id: 'commercial-pm',
    title: 'Commercial Preventive Maintenance',
    slug: 'commercial-pm',
    iconName: 'Wrench',
    shortDescription: 'Annual safety audits, infrared thermography panel scans, and load-balancing analysis for commercial estates.',
    longDescription: 'Prevent costly business downtime and fire hazards. Our preventative maintenance packages are designed for commercial landlords, condo boards, and warehouse operators. We perform complete annual energy audits, thermal scans of main switchboards to catch overheating breakers before they fail, and balance phases to reduce utility demand charges.',
    category: 'commercial',
    startingPrice: 'By Agreement',
    features: [
      'Infrared thermographic surveys with comprehensive reports',
      'Phase load-balancing scans to decrease energy waste',
      'Torque testing and clean-out of electrical switchgear',
      'Emergency egress lighting testing and battery certifications',
      'Power quality logging to trace surges and sag issues',
    ],
    testimonial: {
      quote: 'Their preventive maintenance program is stellar. The thermal imaging scan caught an overheating 100A commercial breaker that was about to fail, saving us from a massive warehouse shutdown.',
      author: 'Liam Tremblay',
      location: 'Vaughan, ON',
    },
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    author: 'Liam Tremblay',
    role: 'Operations Director',
    location: 'Vaughan, ON',
    rating: 5,
    content: 'We hired Breevo Electric for a preventative maintenance audit of our warehousing facility. Their certified team was exceptionally thorough, executing thermographic scans on dozens of panels. They found and replaced an overloaded breaker that was on the verge of failure, preventing a multi-million dollar warehouse shutdown. Truly outstanding engineering.',
    date: 'June 12, 2026',
    verified: true,
  },
  {
    id: '2',
    author: 'Sarah Jenkins',
    role: 'Creative Director, BlueSpace Agency',
    location: 'King West, Toronto',
    rating: 5,
    content: 'Our new loft office required complex exposed-conduit electrical design and custom architectural drop lighting. Breevo brought a level of precision we had never seen before in a contractor. Conduits were bent at perfect right angles and aligned like art. The team worked overnight to meet our launch deadline without leaving a single speck of dust. Highly recommended!',
    date: 'May 30, 2026',
    verified: true,
  },
  {
    id: '3',
    author: 'David Choy',
    role: 'Custom Home Builder',
    location: 'Markham, ON',
    rating: 5,
    content: 'As a luxury home builder, I need sub-trades who understand ultra-high-end specifications and respect high-end finishes. Breevo has been our exclusive electrical partner for three years. Their panel wiring is flawless, they understand complex Lutron configurations inside and out, and they treat our clients with utmost respect. A ten-star partner.',
    date: 'April 14, 2026',
    verified: true,
  },
  {
    id: '4',
    author: 'Amélie Desrosiers',
    role: 'Discerning Homeowner',
    location: 'Rosedale, Toronto',
    rating: 5,
    content: 'Upgrading the electrical in a designated historical house in Rosedale can be a nightmare. Breevo handled the entire process with grace. They upgraded our panel to 200A and installed a complete Lutron smart home system without damaging any historic crown molding. They are extremely tidy, polite, and absolute masters of their craft.',
    date: 'March 22, 2026',
    verified: true,
  },
  {
    id: '5',
    author: 'Marcus Vance',
    role: 'Real Estate Developer',
    location: 'Forest Hill, Toronto',
    rating: 5,
    content: 'We had multiple Level 2 chargers installed across our residential properties. Breevo set up advanced DCC load controllers that seamlessly share power across cars, avoiding the massive cost of a city-utility vault upgrade. The billing was perfectly transparent, and the final look is exceptionally clean. They represent the pinnacle of GTA trade services.',
    date: 'February 10, 2026',
    verified: true,
  },
  {
    id: '6',
    author: 'Elena Petrova',
    role: 'Resident',
    location: 'The Kingsway, Toronto',
    rating: 5,
    content: 'We woke up to flickering lights and a strange burning smell near our utility closet on a Sunday morning. The Breevo technician arrived in under an hour, identified an arc-faulting circuit breaker using a premium thermal scanner, and safely replaced it. They saved our home from a potential fire and explained everything so clearly. Unbeatable peace of mind.',
    date: 'January 18, 2026',
    verified: true,
  },
  {
    id: '7',
    author: 'Gurpreet Singh',
    role: 'Estate Owner',
    location: 'Mississauga, ON',
    rating: 5,
    content: 'Breevo did the wiring for our swimming pool, premium hot tub, and backyard cabana kitchen. The compliance with outdoor bonding codes is strict in Ontario, and the Breevo crew took zero shortcuts. They handled the permit inspections flawlessly, and even color-matched the exterior conduit to our stone accent wall. Incredible attention to detail!',
    date: 'November 15, 2025',
    verified: true,
  },
  {
    id: '8',
    author: 'Robert Higgins',
    role: 'Retired Engineer',
    location: 'Oakville, ON',
    rating: 5,
    content: 'Being a retired civil engineer, I am notoriously critical of trade work. I watched the Breevo team remediate the legacy aluminum wiring in our home. I was thoroughly impressed by their strict adherence to code, the use of genuine AlumiConn connectors, and the calibrated torque drivers used for each screw. They are true professionals who respect physics.',
    date: 'October 04, 2025',
    verified: true,
  },
];

export const GALLERY_PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'Forest Hill Modern Estate',
    category: 'residential',
    location: 'Forest Hill, Toronto',
    description: 'Full electrical engineering for a 9,000 sq ft custom-built luxury home. Features Lutron Palladiom controls, custom low-voltage lighting, and a state-of-the-art dual 400A service entry.',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=1000',
    completionYear: '2025',
    scope: ['400A Dual Service Panel Upgrade', 'Lutron Palladiom Smart Home Scenes', 'Architectural Recessed Lighting Design', 'Invisible In-Wall Subwoofers & Speaker Power'],
  },
  {
    id: 'p2',
    title: 'Financial District Corporate Suite',
    category: 'commercial',
    location: 'Bay Street, Toronto',
    description: 'Complete commercial electrical fit-out for a prestige venture capital firm. Integrates premium acoustics lighting, emergency backups, custom server cabinet distribution, and conference room media power.',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1000',
    completionYear: '2025',
    scope: ['Power Distribution & Dedicated Server Feeders', 'Smart Conference Room Lutron Controls', 'Architectural Task Taskbar Lighting', 'Commercial Fire Safety Interface Integration'],
  },
  {
    id: 'p3',
    title: 'Tesla Elite Garage System',
    category: 'specialty',
    location: 'Oakville, ON',
    description: 'A multi-charger EV installation with dual Tesla Wall Connectors, smart load controllers, and integrated battery backup systems styled with premium carbon panels.',
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=1000',
    completionYear: '2026',
    scope: ['Dual 80A Tesla Wall Connectors', 'DCC-12 Smart Load Allocators', 'Tesla Powerwall Integration', 'Custom Premium Surface Conduit Layout'],
  },
  {
    id: 'p4',
    title: 'Rosedale Restoration Lighting',
    category: 'residential',
    location: 'Rosedale, Toronto',
    description: 'Careful preservation-sensitive lighting design for a heritage-designated Edwardian residence. Upgraded vintage wiring to modern compliance while preserving plaster details.',
    imageUrl: 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&q=80&w=1000',
    completionYear: '2025',
    scope: ['Premium Knob-and-Tube Remediation', 'Lutron RA3 Wireless Control Upgrade', 'Friction-fitted Custom Conduit Chases', 'Fine Art Accent Gallery Projector Lights'],
  },
  {
    id: 'p5',
    title: 'Waterfront Outdoor Entertainment Cabana',
    category: 'specialty',
    location: 'Mississauga, ON',
    description: 'High-safety waterfront wiring for a major outdoor landscape expansion, featuring a luxury infinity pool, gas fireplace automated valves, and high-fidelity outdoor audio.',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=1000',
    completionYear: '2026',
    scope: ['Sub-surface Equipotential Grounding Grid', 'Marine-grade 100A Outdoor Subpanel', 'Bose Waterfront Smart Audio Feeders', 'Automated App-Controlled Landscape Uplighting'],
  },
  {
    id: 'p6',
    title: 'Yorkville Boutique Retail Space',
    category: 'commercial',
    location: 'Yorkville, Toronto',
    description: 'High-fashion retail electrical architecture, focusing on CRI-perfect product lighting, active customer tracks, and ultra-high speed fiber backbone feeds.',
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=1000',
    completionYear: '2025',
    scope: ['98+ CRI Product Spotlight Systems', 'Bespoke Counter Invisible POS Power Feeds', 'Premium Centralised Automation Panel', 'Smart Security/CCTV Isolated Power Grid'],
  },
];

export const BEFORE_AFTER_CASES = [
  {
    title: 'Forest Hill Electrical Panel Upgrade',
    description: 'We replaced an unsafe, overcrowded 1970s fuse panel with a beautifully ordered, modern 200A breaker service with smart surge protection. Every single wire is straight-aligned and clearly labeled.',
    beforeImage: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&q=80&w=800', // representative complex/cluttered look
    afterImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=800', // representative pristine wire job
  },
  {
    title: 'Living Room Architectural Lighting Accent',
    description: 'A dark, dated Rosedale salon converted into a warm, gallery-grade exhibition room using Lutron smart dimmers, precise ceiling pinspots, and subtle warm-white cove LEDs.',
    beforeImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800&blur=5',
    afterImage: 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&q=80&w=800',
  }
];

export const OUR_PROCESS_STEPS = [
  {
    step: '01',
    title: 'Consultation & Thermal Audit',
    description: 'We begin with an exhaustive assessment of your properties’ structural wiring, employing high-resolution thermal imaging to diagnose invisible hotspots.',
  },
  {
    step: '02',
    title: 'Engineering & Transparent Estimate',
    description: 'We draft a precise CAD blueprint of your electrical paths, providing a detailed itemized proposal with transparent pricing and zero hidden fees.',
  },
  {
    step: '03',
    title: 'Elite Craft-Grade Execution',
    description: 'Our licensed master electricians complete the project with surgical precision. We protect all floors, utilize dust-containment shrouds, and align wires like art.',
  },
  {
    step: '04',
    title: 'ESA Certification & Lifetime Guarantee',
    description: 'We manage all Electrical Safety Authority (ESA) inspection filings. Once approved, we issue our hallmark Lifetime Workmanship Warranty.',
  },
];

export const FAQS: FAQItem[] = [
  {
    id: 'f1',
    question: 'Are your electricians fully licensed and insured in Ontario?',
    answer: 'Absolutely. Breevo Electric operates under Master License #7014832, registered with the Electrical Contractors Registration Agency (ECRA) and the Electrical Safety Authority (ESA). We carry $5,000,000 in comprehensive Commercial General Liability Insurance and full WSIB coverage for our entire crew.',
    category: 'general',
  },
  {
    id: 'f2',
    question: 'What is the Electrical Safety Authority (ESA) permit process?',
    answer: 'In Ontario, almost all electrical installations require an ESA permit and subsequent inspection. Breevo Electric manages 100% of this workflow for you. We file the permit before work begins, coordinate with the ESA inspector to visit your property, answer any questions, and hand you the official ESA Certificate of Acceptance once finalized.',
    category: 'general',
  },
  {
    id: 'f3',
    question: 'How long does a typical 200A service panel upgrade take?',
    answer: 'The physical swap and safety grounding take approximately 6 to 8 hours. We coordinate with Toronto Hydro (or your local utility) to disconnect the power in the morning and reconnect it in the afternoon. Your home will only be without electricity for part of a single day, and we clean up so thoroughly you will never know we were there.',
    category: 'services',
  },
  {
    id: 'f4',
    question: 'Why should I worry about aluminum wiring in my home?',
    answer: 'Aluminum wiring was commonly used in homes built between 1965 and 1976. Over time, aluminum expands and contracts at a higher rate than copper, which leads to loose connection terminals at switches and receptacles. These loose connections create arc faults and represent a high fire danger. Our certified pigtailing remediation permanently solves this risk.',
    category: 'safety',
  },
  {
    id: 'f5',
    question: 'What is a load management system (like DCC) for EV chargers?',
    answer: 'If your home is currently on 100-amp service, adding a fast Level 2 EV charger (which draws 40-50 amps) could overload your panel if multiple major appliances run together. A DCC system is an intelligent load monitor. It detects when your home is near peak load and temporarily slows down or pauses EV charging. This allows you to safely charge your car without paying $5k-$10k for an immediate utility service upgrade.',
    category: 'specialty',
  },
  {
    id: 'f6',
    question: 'How much do you charge for diagnostic emergency service calls?',
    answer: 'Our standard dispatch rate for certified diagnostics is $180 CAD for the first hour of master-level troubleshooting, and $120/hr thereafter (excluding materials). We will identify the root cause of the issue, explain the fix, and provide a binding quote before performing any repairs.',
    category: 'pricing',
  },
  {
    id: 'f7',
    question: 'Does Lutron home automation work with existing old house wiring?',
    answer: 'Yes! Lutron RA3 and Caséta are designed to operate wirelessly and are incredibly versatile. In older homes that lack a neutral wire in light switches, Lutron offers specialized no-neutral dimmer models that operate beautifully. We can retroactively turn a 1920s estate into a fully programmed smart home with zero drywall damage.',
    category: 'specialty',
  },
];

export const AREAS_WE_SERVE = [
  'City of Toronto (Downtown, Rosedale, Forest Hill, The Annex, Leslieville)',
  'Etobicoke & The Kingsway',
  'Mississauga & Lorne Park',
  'Oakville & Bronte',
  'Burlington & Tyandaga',
  'Vaughan & Woodbridge',
  'Richmond Hill',
  'Markham & Unionville',
  'North York & Bridle Path',
  'Scarborough & Pickering border',
];
